### ISSUE TITLE
'/code/index.js' is missing.

### ISSUE THREAD

**Issue by samuelgsrmgc** [lisonge/serverless-http-forward#1]
你好，请问部署时出现
{"errorMessage":"Module '/code/index.js' is missing.","errorType":"FunctionUnhandledError: ImportModuleError","stackTrace":["ImportModuleError: Module '/code/index.js' is missing."]}
请问如何处理。

**Comment by lisonge** [comment]
@samuelgsrmgc 这个项目快一年了，我看看你说的这个问题

**Comment by lisonge** [comment]
@samuelgsrmgc 
不好意思，我没有复现你说的问题
我的部署步骤如下
```shell
git clone https://github.com/lisonge/serverless-http-forward.git
cd serverless-http-forward
pnpm i
pnpm run build
# 然后把除了 .git 和 node_modules 的所有文件压缩成一个 serverless-http-forwar.zip
# 然后在 函数计算 香港地区 新建一个 node14 HTTP函数，配置函数入口 index.aliyunHandler
# 上传刚刚的压缩包即可部署，后续可以绑定自定义域名
```

**Comment by lisonge** [comment]
当我 勾选 《使用 fcapp.run 域名测试函数》时，在线调用直接超时

当我不勾选 《使用 fcapp.run 域名测试函数》，我的日志输出里显示函数已经执行完毕，但是返回这个错误
```json
{
    "ErrorCode": "PathNotSupported",
    "ErrorMessage": "'GET' against '/' is not supported"
}
```
要不就是我太菜，要不就是 阿里云函数计算太几把难用了，应该是我有什么隐藏的选项没有开启

**Comment by samuelgsrmgc** [comment]
按照你提供的安装步骤，可以部署成功，现在也是返回错误，绑定自己的域名也不行。
其实就想转一下telegram API，我去看看GCP或者AWS实现吧。谢谢你。

**Comment by lisonge** [comment]
没事，我的 https://github.com/lisonge/aliyun-pages-proxy.git 也是基于这个，目前还在运行

我迟早要升级到这步，我一会看看后再给你解决方案吧

**Comment by lisonge** [comment]
@samuelgsrmgc 
抱歉，确实是我的问题，我发现我的代码里根本没有用到 config.forward_url
导致 url 请求的时候去请求 req.host 会直接请求原来的 url 也就是 https://1887623261562936.cn-hongkong.fc.aliyuncs.com/ 或者 https://forwardsonge-li-http-forward-fequcvipvk.cn-hongkong.fcapp.run/ ，因此就会出现 
```json
{
    "ErrorCode": "PathNotSupported",
    "ErrorMessage": "'GET' against '/' is not supported"
}
```
我加个额外的拦截器修改 url 即可

**Comment by lisonge** [comment]
https://github.com/lisonge/serverless-http-forward/releases/tag/v2.0.0

**Comment by samuelgsrmgc** [comment]
谢谢，已部署成功。
